### ISSUE TITLE
.jar file of this library

### ISSUE THREAD

**Issue by nselimko** [Cutta/MultipleImagePicker#1]
How can i use this library on eclipse,how to get .jar file.
Thank you.

**Comment by Cutta** [comment]
In Eclipse you can import these java files in your project.
https://github.com/Cutta/MultipleImagePicker/tree/master/app/src/main/java/com/cunoraz/pickImages
After that for using it , follow here: 
https://github.com/Cutta/MultipleImagePicker#usage

**Comment by nselimko** [comment]
Thank you(Tesekurler)

**Comment by Cutta** [comment]
You are welcome
